### PR TITLE
Proposed Accept/Content-Type header-based versioning

### PR DESCRIPTION
**Pull request by jmarshall**
Partial proposal for versioning — other aspects are versioning/magic numbers within the JSON text, to be addressed separately.  See discussion in #207.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM.

**Comment by jmtcsngr** [comment]
Any chance we can expect semantic versioning? Somenthing like:
```
application/vnd.ga4gh.htsget.v0.2.0-rc+json
```
Will make it a lot easier to automate checking/resolving supported version in the future.

**Comment by jmarshall** [comment]
What the version number actually is and how/when it is bumped is orthogonal to this pull request.  The text added just reflects the existing version number in the title of the document: _Htsget retrieval API spec v0.2rc_.

Fear not.  Everyone on the planet is familiar with semantic versioning.

**Comment by AlexanderSenf** [comment]
+1

**Comment by vadimzalunin** [comment]
👍

**Comment by mlin** [comment]
LGTM

**Comment by daviesrob** [comment]
I'm happy with this.

**Pull request merged**
