### PR TITLE
fix styles

### PR DESCRIPTION
**Pull request by bicycle1885**
I guess this is what you intended to be.

### CODE REVIEW

**Comment by mp15** [comment]
@jkbonfield @vadimzalunin Could we get a +1 -1 for this so that we can either merge or close?

**Comment by jkbonfield** [comment]
Apologies we did nothing with this.  I'll take a look at it.  It wouldn't surprise me to find a few issues as this TeX doc is the result of an automatic Word to TeX translation (!).

Thanks.

**Comment by jkbonfield** [comment]
Looking at this, I'm unsure if the original text is intentionally done that way.  I suspect so because we have fundamental data types (itf8, arrays, etc) and then more conceptual things utilising those data types (encoding<type>).  Arguably string should be a fundamental type though.

@vadimzalunin - as the original author, I'll punt this to you to let you decide which style you prefer.  I'm happy with it either way.

I do note though that in a lot of places we using ```encoding<int>``` without ever defining ```int```.  I think this is because ```int``` here isn't an actual on-disk type but simply short for an integer value?

**Comment by vadimzalunin** [comment]
Yes, 'int' is a logical type rather than on-disk. 
I think it's ok to merge this.

**Comment by jkbonfield** [comment]
Ok then +1 from me.  Go ahead and merge please Vadim (or ask me to do it if you wish).

**Pull request merged**
