### PR TITLE
Numbers expanded to individual flags

### PR DESCRIPTION
**Pull request by karel-brinda**
Hello,

for readers of the SAM specification, it may be annoying to manually search binary expansions of integers to get the corresponding flags. So I added the expansions.

Karel

### CODE REVIEW

**Comment by nh13** [comment]
@jmarshall seems useful, I am ok with this.

**Comment by karel-brinda** [comment]
Fixed.

**Comment by jmarshall** [comment]
[I have some comments to make on this, so please don't merge it in the meantime.]

**Comment by jmarshall** [comment]
IIRC we discussed something related to this at our last file formats meeting, and concluded that the spec was not in the business of teaching binary arithmetic.  Nonetheless, it would be useful to clarify these examples.

Please see e78064fc638475d7b85821d7fb36db64bcea458b — Karel, does that address the things you wanted to address?

For the initial example, I figure it's even more useful to tell the new reader what the flags are supposed to mean.  Conversely I just added hex equivalents for the 5'/middle/3' fragment stuff, as IMHO writing out the full expansion hides the information that the example is trying to convey.

**Comment by karel-brinda** [comment]
Yes, now it is perfect.

**Comment by jmarshall** [comment]
Thanks, I've merged that one now.  I suspect our “not in the business of teaching binary arithmetic” discussion was in response to #55.

**Pull request closed without merging**
