### PR TITLE
htsget.md: add table of contents

### PR DESCRIPTION
**Pull request by mlin**
Long-delayed follow-through on #346

### CODE REVIEW

**Review by jmarshall — APPROVED** [review]
LGTM. The experience from perusing the refget spec is that this TOC with links is — unsurprisingly! — very useful.

**Review by daviesrob — APPROVED** [review]
Looks like it works:

image

**Comment by jmarshall** [comment]
We could perhaps put `{:.no_toc}` on the POST / Request body / Example subsubsection, and it looks like we might want to check the heading level of Reliability Considerations and Security Considerations. But happy to leave those for a followup…

**Comment by mlin** [comment]
@daviesrob May I trouble you to check how the TOC looks with the recent updates? (CircleCI still wants the keys to the kingdom when I click over there) Thanks!

**Comment by jmarshall** [comment]
CircleCI only generates previews of the PDFs, not these markdown pages. (It could in principle, by spinning up server environments for active PRs as [github/docs](https://github.com/github/docs)'s automation does, but I'm not volunteering :smile:)

You can preview it in your own forked repository by (temporarily) activating your own GitHub Pages at https://github.com/mlin/hts-specs/settings/pages using the PR branch (**htsget-toc**).

**Comment by daviesrob** [comment]
It looks like the changes worked as expected:
image

**Pull request merged**
