### PR TITLE
Matt is no longer a maintainer

### PR DESCRIPTION
**Pull request by andrewyatz**
Removing Matt Laird as a maintainer of refget

### CODE REVIEW

**Comment by jmarshall** [comment]
I did wonder whether this was intended in #432…

Does refget wish to record @lairdm's contribution via “Past refget maintainers include…”?

**Comment by ohofmann** [comment]
> Does refget wish to record @lairdm's contribution via “Past refget maintainers include…”?

Very much so.

**Comment by jmarshall** [comment]
Re-upping the discussion on this small PR, which doesn’t appear to have been considered when the PR was merged. (@andrewyatz)

**Comment by andrewyatz** [comment]
Sorry John very right I missed that.

**Comment by jmarshall** [comment]
There's certainly no need for commits or PRs doing an explicit revert. A follow-up commit is fine.

Your option 3 (a follow-up commit directly on **master** by the refget maintainers) is entirely in accordance with [MAINTAINERS.md](https://github.com/samtools/hts-specs/blob/master/MAINTAINERS.md#updating-the-specifications): it's both uncontroversial and already-discussed.

**Comment by andrewyatz** [comment]
Thank you will do this now

**Comment by jkbonfield** [comment]
Somewhere in the middle of that I stupidly remembered it's time I updated the CRAM pdf ;-)

If it needs redoing again that's such a trivial task it's a non-issue, but I assume we're not talking about actual rollbacks and are just having a bit more conversational commit history.

**Pull request merged**
