### PR TITLE
Split out tags into separate document

### PR DESCRIPTION
**Pull request by jmarshall**

### CODE REVIEW

**Comment by jkbonfield** [comment]
Good and obvious first change (thanks), but we need to go through with expanded explanations of the various fields, which probably means quite a bit of discussion (some aren't *clear*).

**Comment by tfenne** [comment]
@jmarshall is there a plan for finalizing this split into a separate core spec and tags document?  It would be nice to get this finalized so that the process of adding new tags can be unblocked.  If there is work that needs to be done and can be described in issues or `todo`s in the new document I'm happy to pitch in.

**Comment by nh13** [comment]
@jmarshall want someone to look over this before merging?

**Comment by nh13** [comment]
Oops, looks like it got merged in!

**Comment by jmarshall** [comment]
Merged as ratified at the the June file formats meeting.

As noted in @jkbonfield's comment and in the commit messages (“This facilitates expanding the tag explanations so that they become actually *clear*, but this remains a work-in-progress”) this is the basis of the document, but in our copious spare time it would be good to expand the explanations so they actually communicate the details necessary to use some of these tags.

**Pull request merged**
