### PR TITLE
Refresh htsget interop site

### PR DESCRIPTION
**Pull request by brainstorm**
The other endpoints seem to be either old (htsget ~0.2) or having SSL certificate issues. So this site needs a bit of a refresh in order to have htsget developers interact with endpoints that are up to date (i.e: supporting /service-info).

Might be useful to have the administrative contact info for those endpoints handy somewhere (perhaps on that same page?).

/cc @mlin @jb-adams @ohofmann

### CODE REVIEW

**Comment by brainstorm** [comment]
There are some asset retrieval issues too:

Screen Shot 2020-11-09 at 11 25 49 am

**Comment by jb-adams** [comment]
Thanks @brainstorm !

Additionally, I'd like to get the currently running servers registered on the [GA4GH service registry](https://github.com/ga4gh/ga4gh-registry). It's a general-purpose registry of web services implementing GA4GH standards using the service registry specification. [OpenAPI](https://ga4gh.github.io/ga4gh-registry/docs/index.html)

example requests:
`https://registry.ga4gh.org/v1/services`
`https://registry.ga4gh.org/v1/services?type=org.ga4gh:htsget:*`

For `htsget`, only the GA4GH server is currently registered. But I'd like to get multiple servers registered for interop, testing, FASP, visibility, etc.

Any chance we could work on this?

**Comment by brainstorm** [comment]
Better than additionally, wouldn't it make sense to have this interop page just pointing exclusively to the GA4GH service registry for htsget? Perhaps cleaner to not update the same things on several places? :)

**Comment by jb-adams** [comment]
@brainstorm I like that idea! Let's discuss at the next htsget meeting

**Comment by mlin** [comment]
@jb-adams @brainstorm Yea, this interop page was created before service registry existed, and can now be largely retired as vestigial

**Comment by jmarshall** [comment]
:+1: to just delete this page.

**Comment by brainstorm** [comment]
Done.

**Pull request merged**
