### PR TITLE
Add ELEMENT to PL header tag

### PR DESCRIPTION
**Pull request by ryankelley-lm**
This is a request to add ELEMENT to the controlled vocabulary for the PL header tag

### CODE REVIEW

**Comment by blajoie-elembio** [comment]
Background on the Element AVITI instrument.
https://www.elementbiosciences.com/products/aviti

Additional instrument specifications here:
https://www.elementbiosciences.com/resources/marketing
https://www.elementbiosciences.com/news/agbt-2022

@jmarshall @jkbonfield -  happy to attend the meeting on the 21st to discuss further!

**Comment by jkbonfield** [comment]
Thanks for this.  It looks like an uncontraversial change.

The only debatable topic would be whether `ELEMENT` or `AVITI` is the correct name.  For now the two are synonymous as you have a single technology.  If AVITI is a product name and it's likely you'll be producing multiple products but all with a similar sequencing error model (such as Illumina HiSeq, NextSeq, NovaSeq, etc) then ELEMENT is likely appropriate.  We've been a bit flexible in the past, but tend to prefer "technology" here, as a company may release instruments with completely new technologies.  (However it wouldn't be the end of the world if ELEMENT referred to the first technology and something else is used in any subsequent ones if they arrive.)

I've added it to the list of things to discuss at the next GA4GH File Formats meeting, which naturally you're welcome to attend if you wish.

**Comment by blajoie** [comment]
Thanks @jkbonfield.  We will discuss internally and can provide an update at the next GA4GH meeting.  As you suggest, using AVITI may be more appropriate and forward looking.

Can you share the details re. the meeting invite?

bryan.lajoie at elembio.com

**Comment by blajoie-elembio** [comment]
Just noticed that the meeting is tomorrow :). Any updates on the meeting invite / details? 

I also just sent Reggan (contact for the Large Scale Genomics work stream) an email.

**Comment by jkbonfield** [comment]
> Just noticed that the meeting is tomorrow :). Any updates on the meeting invite / details?
> 
> I also just sent Reggan (contact for the Large Scale Genomics work stream) an email.

The agenda / minutes are at https://docs.google.com/document/d/1EgaY-1rRMI6mD2IASlyUH5hQkkTcL71Q/edit#

If you haven't got an invite link to the zoom call from Reggan yet, drop me an email via jkb at sanger ac uk.  The same obviously goes for anyone else needing to join in.  I'm unsure if the zoom calls are public, but can ask Reggan.  If so, they should be added to the agenda.

**Comment by blajoie-elembio** [comment]
All set!  Reggan sent over the invite

**Pull request merged**
