### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by cmdcolin**
Typos found using https://github.com/crate-ci/typos (a very nice tool if you ask me!). I also saw https://github.com/samtools/hts-specs/pull/691 and was motivated to run it across codebase.

The typo checking could also become a part of a github workflow on this repo, but that is not added by this PR

### CODE REVIEW

**Comment by jkbonfield** [comment]
Thank you for these.  Generally it's best to produce separate PRs for the different groups - Refget, crypt4gh, fileformats (SAM,BAM,CRAM,VCF,BCF).  The reason is that different maintainers are involved.  The issues look trivial though so not really contentious.

We have a File Formats meeting this afternoon so can discuss then, but we may just cherry pick appropriate chunks related to us and leave the other groups to do the same.  Will decided later.

**Comment by cmdcolin** [comment]
rebased onto latest master. unsure why CI failed though

**Comment by cmdcolin** [comment]
similar CI error on https://github.com/samtools/hts-specs/pull/684/files

**Comment by jkbonfield** [comment]
I've been seeing similar CI failures recently.  I'm not sure on the cause, but maybe @jmarshall will know?

It's failing on this:

```
! Undefined control sequence.
\@date ->\headdate 
```

`\headdate` is coming from new/*.ver files, generated by scripts/genversion.sh.  I see in the logs:

```
mkdir new
scripts/genversion.sh CRAMv2.1.tex img/CRAMFileFormat2-1-fig001.png img/CRAMFileFormat2-1-fig002.png img/CRAMFileFormat2-1-fig003.png img/CRAMFileFormat2-1-fig004.png img/CRAMFileFormat2-1-fig005.png img/CRAMFileFormat2-1-fig006.png img/CRAMFileFormat2-1-fig007.png > new/CRAMv2.1.ver
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

latexmk --pdf --pdflatex='pdflatex'  --output-directory=new CRAMv2.1.tex
	git config --global --add safe.directory /github/workspace
```

So it's possible this change is due to some github/latex update which has gained additional security checks.

**Pull request closed without merging**
