### PR TITLE
Add GA4GH retrieval API spec

### PR DESCRIPTION
**Pull request by jmarshall**
This adds a markdownified version of the previous [Google Docs document](https://docs.google.com/document/d/1OSPfxdJ3uPoCfUVzMaekCOPF5sNEwqkJEUj-SjlECy0).

You can preview the markdown text in this PR, the basically-rendered source repo [here](https://github.com/jmarshall/hts-specs/blob/ga4gh/ga4gh-retrieval.md), and the fully-rendered gh-pages version [here](http://jmarshall.github.io/hts-specs/ga4gh-retrieval.html) or as linked from <http://jmarshall.github.io/hts-specs/> (use the link in the sidebar).

There are (currently) four annotations on the Google Docs document, which I've turned into footnotes here.  I imagine that we'll want to turn them into issues or so, and delete the markdown footnotes as we resolve them.

### CODE REVIEW

**Comment by dglazer** [comment]
Minor formatting issues (as seen in Github's "view" option on the PR):
- the table of HTTP error codes isn't rendering
- there are some italic comments on the request/response fields that aren't showing up
- the list of clarification suggestions isn't rendering

**Comment by jmarshall** [comment]
There are two flavours of markdown in play here: GH-flavoured Markdown as used in GitHub's "view" options and source repository view; [kramdown](http://kramdown.gettalong.org/) as used by GitHub Pages.  At the November meeting we didn't say which flavour we had in mind, but the question is answered by virtue of the spec document containing things like nested tables with paragraphs inside that simply can't be expressed in GH-flavoured plain markdown.

So the place to see the fully-formatted document is the **gh-pages** version of it.  All the minor issues noted by @dglazer are limitations of of GitHub's "view" rendering, and can't be worked around without dropping down to raw HTML.  And we said we wanted a markdown document, not an HTML document :smile:.

**Comment by jmarshall** [comment]
We are already using raw HTML tables for the nested tables, so it would be possible to use HTML `<table>` for the tables of HTTP error codes and fields too and have them also visible in the GitHub source "view" renderings.  Pros and cons are as noted in 6c41a52ec8b3705e8c5fe2fbe3f29227562f13d5: simple editing vs. source/"view" renderings.

But the other things you noted, especially the italics etc within the raw HTML table, are not fixable in the GitHub source/"view" rendering.

**Comment by pgrosu** [comment]
@jmarshall and @dglazer:  Thank you for making this available, as it will help with understanding the basis of the implementation.  Will this be the page that everyone should check as the central point of the protocol definition, or is the Google Doc the main location?  Does the group have a discussion group link?

@jmarshall:  You can embed HTML code in Github's markdown.  Below is the example, and following it is the code that is based on the HTML you generated :)

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>HTTP status code</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>InvalidAuthentication</td>
      <td>401</td>
      <td>Authorization provided is invalid</td>
    </tr>
    <tr>
      <td>PermissionDenied</td>
      <td>403</td>
      <td>Authorization is required to access the resource</td>
    </tr>
    <tr>
      <td>NotFound</td>
      <td>404</td>
      <td>The resource requested was not found</td>
    </tr>
    <tr>
      <td>Unable</td>
      <td>406</td>
      <td>The server is unable to fulfill the request</td>
    </tr>
    <tr>
      <td>UnsupportedFormat</td>
      <td>409</td>
      <td>The requested file format is not supported by the server</td>
    </tr>
    <tr>
      <td>InvalidInput</td>
      <td>422</td>
      <td>The request parameters do not adhere to the specification</td>
    </tr>
    <tr>
      <td>InternalError</td>
      <td>500</td>
      <td>Server error, clients should try later</td>
    </tr>
    <tr>
      <td>ServiceUnavailable</td>
      <td>503</td>
      <td>Service is temporarily unavailable</td>
    </tr>
  </tbody>
</table>

The HTML code:

```HTML
<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>HTTP status code</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>InvalidAuthentication</td>
      <td>401</td>
      <td>Authorization provided is invalid</td>
    </tr>
    <tr>
      <td>PermissionDenied</td>
      <td>403</td>
      <td>Authorization is required to access the resource</td>
    </tr>
    <tr>
      <td>NotFound</td>
      <td>404</td>
      <td>The resource requested was not found</td>
    </tr>
    <tr>
      <td>Unable</td>
      <td>406</td>
      <td>The server is unable to fulfill the request</td>
    </tr>
    <tr>
      <td>UnsupportedFormat</td>
      <td>409</td>
      <td>The requested file format is not supported by the server</td>
    </tr>
    <tr>
      <td>InvalidInput</td>
      <td>422</td>
      <td>The request parameters do not adhere to the specification</td>
    </tr>
    <tr>
      <td>InternalError</td>
      <td>500</td>
      <td>Server error, clients should try later</td>
    </tr>
    <tr>
      <td>ServiceUnavailable</td>
      <td>503</td>
      <td>Service is temporarily unavailable</td>
    </tr>
  </tbody>
</table>
```

Hope it helps and many thanks again!
`p

**Comment by jeromekelleher** [comment]
Looks good to me.

**Comment by dglazer** [comment]
@jmarshall -- thanks for explaining. As long as the formatting issues I mentioned aren't issues in the final published form, the doc looks good to me.

Minor notes:
- Is there a preview link somewhere that I missed that lets people review that final form? Or do we have to wait until it's submitted to see it?
- Too bad we have to choose between rich formatting and easy preview/editing, but you've settled on a pretty reasonable mix, where we mostly get the best of both.

**Comment by jmarshall** [comment]
Links are at the top of this page, in the first comment / description of this PR.

**Comment by dglazer** [comment]
Doh -- thanks; not sure how I missed that the first time. Yes, LGTM.

**Comment by jmarshall** [comment]
Renamed to “htsget” as voted, and merged.  Thanks to those who looked this over.

**Pull request merged**
