### PR TITLE
[TEST] Testing CI updates

### PR DESCRIPTION
**Pull request by jmarshall**

### CODE REVIEW

**Comment by jmarshall** [comment]
It seems that Cheng Xu's image is missing both `make` and `git`, which complicates just moving to it…

**Comment by lbergelson** [comment]
@jmarshall What's the advantage of the new image?  If you want to switch to it I'd recommend we bake a new custom image based on that with the tools we need added in already.

**Comment by jmarshall** [comment]
The advantage of using someone else's image is that we don't have to maintain an image ourselves. In particular, [xu-cheng/latex-docker](https://github.com/xu-cheng/latex-docker) is automatically rebuilt periodically, so we'd go from an outdated image to one automatically kept up to date.

But this PR was really just me experimenting with the quick update to get this going again — so really I should get back to it if it's supposed to be a quick fix! :smile: If you want to build an updated image please feel free.

However this is a bit of a stopgap. I have also been looking at reimplementing this on GitHub Actions and using a different method to attach the PDFs to PR comments (thus solving #555) — see another stalled experiment in my [jmarshall/actions branch](https://github.com/jmarshall/hts-specs/tree/actions).

**Comment by michaelmhoffman** [comment]
Are you still thinking about updating the TeX environment? I am still getting build failures on #570 because I am using features not available in the old TeX Live 2015 installation on CircleCI.

**Comment by michaelmhoffman** [comment]
Could we please discuss on the 2021-10-14 meeting? I would tag Amreen but I can't figure out her GitHub username.

**Comment by michaelmhoffman** [comment]
A recent enough TeX Live should be included in recent Ubuntu releases (21.04 or 21.10). Unfortunately, I don't think the last LTS release (20.04) is recent enough, and don't know how difficult it is to get a non-LTS Ubuntu image for CircleCI.

**Comment by jmarshall** [comment]
Experiments continue on jmarshall/hts-specs#1, which is almost ready to land. In summary:

1. Uses GitHub Actions; we can retire the Circle CI integration.
2. Stores the PDFs as commits in the hts-specs repository (not on a branch, so that they are not fetched by default; on a ref, so they are not garbage collected), thus solving #555.
3. Currently comments as “**github-actions** (bot)”; we may wish to retire @hts-specs-bot (though the commits do need an author and email address, which currently uses hts-specs-bot's details).

 Happy to discuss the details at tomorrow's meeting, or a PR will be appearing in due course.

**Comment by jmarshall** [comment]
This test PR is now superseded by those continuing experiments, which are now #641.

**Pull request closed without merging**
