### PR TITLE
Clarify SAM file encoding (mostly ASCII, some UTF-8 parts)

### PR DESCRIPTION
**Pull request by jmarshall**
Draft text clarifying the paragraph around file encoding, locales, and regular expressions.
Addresses #664.

I would like to spell it out in the first sentence a bit more but haven't come up with a great wording yet; something like

> SAM files are encoded in UTF-8 using mainly ASCII characters only.

### CODE REVIEW

**Comment by jkbonfield** [comment]
I'm happy with the new text, although I note it's draft still.

PS.  The rendering of the diff PDF is visible in Opera and MS Edge on Windows, but firefox shows the hex codes for unknown font symbol.  I'm not sure what's going on there, but maintainers only need 1 working browser for validation and the final PDF is fine. :)

**Comment by jmarshall** [comment]
I was less happy with the new text, I think because it said it was UTF-8 first and then adjusted it to mostly-ASCII second. I've turned that around again, and moved most of the text out of footnotes, so I think it's clearer and with a more accurate emphasis now.

Unicode adds several more line termination characters, so I added a footnote pointing out that only ASCII line terminators are valid.

And I've proposed a second commit using @jkbonfield's suggestion on #719 of using `[:print:]` in the regex. This might be a good idea, or it might be better to leave the regex as is and add a footnote saying “uh, for UTF-8 field values we actually mean `[ -0xFFFE]` or something”.

**Comment by jmarshall** [comment]
The page breaking is now horrible, splitting the table between VN and SO. I have a followup PR that rearranges the first section a bit to bring both figures in the SAM example back to the first page, which restores the previous better page breaks in the header section.

**Comment by jkbonfield** [comment]
> And I've proposed a second commit using @jkbonfield's suggestion on #719 of using `[:print:]` in the regex. This might be a good idea, or it might be better to leave the regex as is and add a footnote saying “uh, for UTF-8 field values we actually mean `[ -0xFFFE]` or something”.

I'd be wary of attempting to specify unicode with a hex range.  We could, but I'm not 100% sure what "printable" even means in unicode.  Is the block replacement character (FFFD) printable?  It's there for when decoding fails I think.  Also why to FFFE?  There are more beyond that.  𐘬  :-)

I just think it's a hiding to nothing and frankly `[ -0xFFFE]` does nothing to clarify the *intention* of the regular expression.  There is no easy solution here though.

**Comment by jmarshall** [comment]
I've split the second commit adjusting the header regex off as a separate PR, #726.

This PR is now a fairly straightforward clarification to a single paragraph. I'd like to get it merged so that I can prepare the followup formatting improvement PR that affects the same sections. So let's start a one week timer for this one: if there are no objections before then, I will merge this on Friday May 19th.

@jkbonfield: Feel free to review and merge this before then if you wish.

**Comment by jkbonfield** [comment]
Looks good to me, thanks.  I'll merge it.

**Pull request merged**
