### PR TITLE
add SINGULAR to platform tags

### PR DESCRIPTION
**Pull request by omicsorama**
This request is to add Singular Genomics `SINGULAR` to list of platforms

### CODE REVIEW

**Comment by omicsorama** [comment]
thanks!

**Comment by jkbonfield** [comment]
I can answer part of this.  The machine data is available [here](https://go.elementbiosciences.com/access-seq-datasets-060622), and the most recent publication is [here](https://www.biorxiv.org/content/10.1101/2022.11.03.514117v1).   They claim to have started shipping in May 2022, and have a quoted lead time of 4-8 weeks for new installations.  So it feels like a sensible candidate.

Obviously Element Biosciences can comment further on the availability.

**Comment by blajoie** [comment]
> Obviously Element Biosciences can comment further on the availability.
@jkbonfield  - I think you meant Singular.  Singular (G4) and Element Biosciences (AVITI) are separate technologies, instruments and companies :)

**Comment by jkbonfield** [comment]
Argh, you're quite right.  I'm mixing my systems up terribly!  My apologies to both Singular and Element Biosciences (who are already in there).

As for Singular - I don't yet know about data other than their tech report (NA12878 validation, but no link to downloads) or instrument availability.

**Comment by nh13** [comment]
@jkbonfield can you please re-review?

**Comment by jmarshall** [comment]
It would be great if some Singular folk could provide some pointers to reply to the questions in https://github.com/samtools/hts-specs/pull/686#issuecomment-1339746675.

**Comment by shultzaberger** [comment]
Hi @jmarshall.   Thanks for your help. The Singular Sequencer (G4) is available and we have begun shipping. There are applications notes for Bulk RNA-Seq, scRNA-Seq, Whole Human Genome + Exome sequencing with germline variant detection on the Singular website here:  https://singulargenomics.com/resources/ . For now, accompanying data for all tech reports are available for download by request (email care@singulargenomics.com and someone will send a download link), but we are working to moving those data to be directly downloaded through the website. Links to download some of those data sets directly are given below:

RNASeq:	https://singular-public-repo.s3.us-west-1.amazonaws.com/RNASeq_repo/RNA_seq_fastq.tar
scRNA:	https://singular-public-repo.s3.us-west-1.amazonaws.com/scRNA_v2_repo/Singular_scseq_TechReport_Fastqs.tar
human WES:	https://singular-public-repo.s3.us-west-1.amazonaws.com/Singular_WES_TechReport_Repo/Singular_WES_TechReport.tar

Please let me know if you need any additional information or have any issues accessing data. Thanks again

**Pull request merged**
